# Generated by Django 3.1 on 2020-09-03 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200903_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 15, 35, 53, 593734), verbose_name='date published'),
        ),
    ]
